import { Client } from 'ssh2'
import { execCommand } from './ssh'

export const SERVERS_DIR = '/home/server-craft'
const INSTALLER_JAR_PATTERN = '(installer|setup)'
const GENERATED_START_SCRIPT_MARKER = '# Generated by craft-panel'

export interface Server {
  id: string
  name: string
  path: string
  status: 'running' | 'stopped'
}

export async function listServers(client: Client): Promise<Server[]> {
  // Single SSH command: list dirs and check status for each
  const { stdout } = await execCommand(client,
    `mkdir -p ${SERVERS_DIR} 2>/dev/null; ` +
    `for dir in ${SERVERS_DIR}/*/; do ` +
      `[ -d "$dir" ] || continue; ` +
      `name=$(basename "$dir"); ` +
      `status="stopped"; ` +
      `if command -v tmux >/dev/null 2>&1; then ` +
        `if tmux has-session -t "craft-$name" 2>/dev/null; then ` +
          `cmd=$(tmux list-panes -t "craft-$name" -F "#{pane_current_command}" 2>/dev/null); ` +
          `case "$cmd" in bash|sh|zsh|fish|dash|tmux|"") ;; *) status="running" ;; esac; ` +
        `fi; ` +
      `else ` +
        `pgrep -f "java.*${SERVERS_DIR}/$name" >/dev/null 2>&1 && status="running"; ` +
      `fi; ` +
      `echo "$name:$status"; ` +
    `done`
  )

  return stdout
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.includes(':'))
    .map((line) => {
      const [name, status] = line.split(':')
      return {
        id: name,
        name,
        path: `${SERVERS_DIR}/${name}`,
        status: (status === 'running' ? 'running' : 'stopped') as 'running' | 'stopped',
      }
    })
}

export async function getServerStatus(
  client: Client,
  name: string
): Promise<'running' | 'stopped'> {
  // Single SSH command checks tmux availability, session, and pane command
  const { stdout } = await execCommand(client,
    `if command -v tmux >/dev/null 2>&1; then ` +
      `if tmux has-session -t craft-${name} 2>/dev/null; then ` +
        `cmd=$(tmux list-panes -t craft-${name} -F "#{pane_current_command}" 2>/dev/null); ` +
        `case "$cmd" in bash|sh|zsh|fish|dash|tmux|"") echo stopped ;; *) echo running ;; esac; ` +
      `else echo stopped; fi; ` +
    `else ` +
      `pgrep -f "java.*${SERVERS_DIR}/${name}" >/dev/null 2>&1 && echo running || echo stopped; ` +
    `fi`
  )
  return stdout.trim() === 'running' ? 'running' : 'stopped'
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\"'\"'`)}'`
}

function buildMessageCommand(dir: string, lines: string[]): string {
  const quotedLines = lines.map(shellQuote).join(' ')
  return `cd ${shellQuote(dir)} && printf '%s\n' ${quotedLines}`
}

function buildJavaMissingCommand(dir: string): string {
  return buildMessageCommand(dir, [
    'Java was not found on the remote host.',
    'Open the panel setup page to install Java, or install a headless JRE manually.',
    'Expected packages are usually default-jre-headless or java-17-openjdk-headless.',
  ])
}

function buildInstallerHelpCommand(dir: string, installerJar: string): string {
  return buildMessageCommand(dir, [
    `Detected installer JAR: ${installerJar}`,
    'This is not a runnable server JAR yet.',
    'Install it in the server directory first with:',
    `  java -jar ${installerJar} --installServer`,
    'Then start the generated Forge server using run.sh or start.sh.',
  ])
}

async function hasJava(client: Client): Promise<boolean> {
  const { stdout } = await execCommand(client, 'command -v java >/dev/null 2>&1 && echo yes || echo no')
  return stdout.trim() === 'yes'
}

function buildGeneratedStartScript(name: string): string {
  return `#!/bin/bash
${GENERATED_START_SCRIPT_MARKER}
set -e

cd ${SERVERS_DIR}/${name}

if [ -f ./run.sh ]; then
  exec bash ./run.sh
fi

JAVA_BIN=$(command -v java || true)
if [ -z "$JAVA_BIN" ]; then
  echo "Java was not found on the remote host."
  echo "Open the panel setup page or install a headless JRE manually."
  exit 1
fi

INSTALLER_JAR=$(ls *.jar 2>/dev/null | grep -iE '${INSTALLER_JAR_PATTERN}' | head -1)
JAR=$(ls *.jar 2>/dev/null | grep -viE '${INSTALLER_JAR_PATTERN}' | head -1)

if [ -z "$JAR" ]; then
  if [ -n "$INSTALLER_JAR" ]; then
    echo "Detected installer JAR: $INSTALLER_JAR"
    echo "Run: java -jar $INSTALLER_JAR --installServer"
    echo "Then start the generated Forge server."
    exit 1
  fi
  echo "No runnable jar file found in ${SERVERS_DIR}/${name}"
  exit 1
fi

exec "$JAVA_BIN" -Xmx2G -Xms1G -jar "$JAR" nogui`
}

async function writeGeneratedStartScript(client: Client, name: string): Promise<void> {
  const startScript = buildGeneratedStartScript(name)
  await execCommand(
    client,
    `cat > ${SERVERS_DIR}/${name}/start.sh << 'STARTSCRIPT'\n${startScript}\nSTARTSCRIPT`
  )
  await execCommand(client, `chmod +x ${SERVERS_DIR}/${name}/start.sh`)
}

export async function getStartCommand(client: Client, name: string): Promise<string> {
  const serverDir = `${SERVERS_DIR}/${name}`
  const serverDirQuoted = shellQuote(serverDir)

  const { stdout: runSh } = await execCommand(
    client,
    `test -f ${serverDirQuoted}/run.sh && echo exists || echo missing`
  )

  if (runSh.trim() === 'exists') {
    return `cd ${serverDirQuoted} && bash ./run.sh`
  }

  const { stdout: startSh } = await execCommand(
    client,
    `test -f ${serverDirQuoted}/start.sh && echo exists || echo missing`
  )

  const { stdout: runnableJarList } = await execCommand(
    client,
    `cd ${serverDirQuoted} && ls *.jar 2>/dev/null | grep -viE ${shellQuote(INSTALLER_JAR_PATTERN)} | head -1`
  )
  const runnableJar = runnableJarList.trim()

  const { stdout: installerJarList } = await execCommand(
    client,
    `cd ${serverDirQuoted} && ls *.jar 2>/dev/null | grep -iE ${shellQuote(INSTALLER_JAR_PATTERN)} | head -1`
  )
  const installerJar = installerJarList.trim()

  if (startSh.trim() === 'exists') {
    const { stdout: startShPreview } = await execCommand(
      client,
      `sed -n '1,40p' ${serverDirQuoted}/start.sh 2>/dev/null`
    )

    const isGeneratedScript =
      startShPreview.includes(GENERATED_START_SCRIPT_MARKER) ||
      (
        startShPreview.includes('JAR=$(ls *.jar 2>/dev/null | head -1)') &&
        startShPreview.includes('java -Xmx2G -Xms1G -jar "$JAR" nogui')
      )

    if (!isGeneratedScript) {
      return `bash ${serverDirQuoted}/start.sh`
    }

    await writeGeneratedStartScript(client, name)

    if (installerJar && !runnableJar) {
      return buildInstallerHelpCommand(serverDir, installerJar)
    }

    if (!await hasJava(client)) {
      return buildJavaMissingCommand(serverDir)
    }

    return `bash ${serverDirQuoted}/start.sh`
  }

  if (installerJar && !runnableJar) {
    return buildInstallerHelpCommand(serverDir, installerJar)
  }

  if (runnableJar) {
    if (!await hasJava(client)) {
      return buildJavaMissingCommand(serverDir)
    }
    return `cd ${serverDirQuoted} && java -Xmx2G -jar ${shellQuote(runnableJar)} nogui`
  }

  return buildMessageCommand(serverDir, [
    `No start.sh, run.sh, or runnable jar found in ${serverDir}`,
  ])
}

export async function createServer(client: Client, name: string): Promise<void> {
  await execCommand(client, `mkdir -p ${SERVERS_DIR}/${name}`)

  await execCommand(
    client,
    `echo "eula=true" > ${SERVERS_DIR}/${name}/eula.txt`
  )

  await writeGeneratedStartScript(client, name)
}

export async function getServerUptime(client: Client, name: string): Promise<string | null> {
  const { stdout, code } = await execCommand(
    client,
    `tmux display-message -t craft-${name} -p "#{session_created}" 2>/dev/null`
  )

  if (code !== 0 || !stdout.trim()) return null

  const created = parseInt(stdout.trim(), 10)
  if (isNaN(created)) return null

  const uptimeMs = Date.now() - created * 1000
  const uptimeSec = Math.floor(uptimeMs / 1000)

  if (uptimeSec < 60) return `${uptimeSec}s`
  const uptimeMin = Math.floor(uptimeSec / 60)
  if (uptimeMin < 60) return `${uptimeMin}m ${uptimeSec % 60}s`
  const uptimeHr = Math.floor(uptimeMin / 60)
  return `${uptimeHr}h ${uptimeMin % 60}m`
}
